/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin-login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api.admin-logout'
import { Route as ApiAdminSessionRouteImport } from './routes/api.admin-session'
import { Route as ApiDeleteContactRouteImport } from './routes/api.delete-contact'
import { Route as ApiDeleteQuoteRouteImport } from './routes/api.delete-quote'
import { Route as ApiGetContactsRouteImport } from './routes/api.get-contacts'
import { Route as ApiGetQuotesRouteImport } from './routes/api.get-quotes'
import { Route as ApiSubmitContactRouteImport } from './routes/api.submit-contact'
import { Route as ApiSubmitQuoteRouteImport } from './routes/api.submit-quote'
import { Route as ApiUpdateContactRouteImport } from './routes/api.update-contact'
import { Route as ApiUpdateQuoteRouteImport } from './routes/api.update-quote'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin-login',
  path: '/api/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin-logout',
  path: '/api/admin-logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin-session',
  path: '/api/admin-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteContactRoute = ApiDeleteContactRouteImport.update({
  id: '/api/delete-contact',
  path: '/api/delete-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteQuoteRoute = ApiDeleteQuoteRouteImport.update({
  id: '/api/delete-quote',
  path: '/api/delete-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetContactsRoute = ApiGetContactsRouteImport.update({
  id: '/api/get-contacts',
  path: '/api/get-contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetQuotesRoute = ApiGetQuotesRouteImport.update({
  id: '/api/get-quotes',
  path: '/api/get-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitContactRoute = ApiSubmitContactRouteImport.update({
  id: '/api/submit-contact',
  path: '/api/submit-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitQuoteRoute = ApiSubmitQuoteRouteImport.update({
  id: '/api/submit-quote',
  path: '/api/submit-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateContactRoute = ApiUpdateContactRouteImport.update({
  id: '/api/update-contact',
  path: '/api/update-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateQuoteRoute = ApiUpdateQuoteRouteImport.update({
  id: '/api/update-quote',
  path: '/api/update-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/coverage': typeof CoverageRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/delete-contact': typeof ApiDeleteContactRoute
  '/api/delete-quote': typeof ApiDeleteQuoteRoute
  '/api/get-contacts': typeof ApiGetContactsRoute
  '/api/get-quotes': typeof ApiGetQuotesRoute
  '/api/submit-contact': typeof ApiSubmitContactRoute
  '/api/submit-quote': typeof ApiSubmitQuoteRoute
  '/api/update-contact': typeof ApiUpdateContactRoute
  '/api/update-quote': typeof ApiUpdateQuoteRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/coverage': typeof CoverageRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/delete-contact': typeof ApiDeleteContactRoute
  '/api/delete-quote': typeof ApiDeleteQuoteRoute
  '/api/get-contacts': typeof ApiGetContactsRoute
  '/api/get-quotes': typeof ApiGetQuotesRoute
  '/api/submit-contact': typeof ApiSubmitContactRoute
  '/api/submit-quote': typeof ApiSubmitQuoteRoute
  '/api/update-contact': typeof ApiUpdateContactRoute
  '/api/update-quote': typeof ApiUpdateQuoteRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/coverage': typeof CoverageRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/delete-contact': typeof ApiDeleteContactRoute
  '/api/delete-quote': typeof ApiDeleteQuoteRoute
  '/api/get-contacts': typeof ApiGetContactsRoute
  '/api/get-quotes': typeof ApiGetQuotesRoute
  '/api/submit-contact': typeof ApiSubmitContactRoute
  '/api/submit-quote': typeof ApiSubmitQuoteRoute
  '/api/update-contact': typeof ApiUpdateContactRoute
  '/api/update-quote': typeof ApiUpdateQuoteRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/coverage'
    | '/how-it-works'
    | '/industries'
    | '/pricing'
    | '/quote'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-session'
    | '/api/delete-contact'
    | '/api/delete-quote'
    | '/api/get-contacts'
    | '/api/get-quotes'
    | '/api/submit-contact'
    | '/api/submit-quote'
    | '/api/update-contact'
    | '/api/update-quote'
    | '/services/$slug'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/coverage'
    | '/how-it-works'
    | '/industries'
    | '/pricing'
    | '/quote'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-session'
    | '/api/delete-contact'
    | '/api/delete-quote'
    | '/api/get-contacts'
    | '/api/get-quotes'
    | '/api/submit-contact'
    | '/api/submit-quote'
    | '/api/update-contact'
    | '/api/update-quote'
    | '/services/$slug'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/coverage'
    | '/how-it-works'
    | '/industries'
    | '/pricing'
    | '/quote'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-session'
    | '/api/delete-contact'
    | '/api/delete-quote'
    | '/api/get-contacts'
    | '/api/get-quotes'
    | '/api/submit-contact'
    | '/api/submit-quote'
    | '/api/update-contact'
    | '/api/update-quote'
    | '/services/$slug'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CoverageRoute: typeof CoverageRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IndustriesRoute: typeof IndustriesRoute
  PricingRoute: typeof PricingRoute
  QuoteRoute: typeof QuoteRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiDeleteContactRoute: typeof ApiDeleteContactRoute
  ApiDeleteQuoteRoute: typeof ApiDeleteQuoteRoute
  ApiGetContactsRoute: typeof ApiGetContactsRoute
  ApiGetQuotesRoute: typeof ApiGetQuotesRoute
  ApiSubmitContactRoute: typeof ApiSubmitContactRoute
  ApiSubmitQuoteRoute: typeof ApiSubmitQuoteRoute
  ApiUpdateContactRoute: typeof ApiUpdateContactRoute
  ApiUpdateQuoteRoute: typeof ApiUpdateQuoteRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-login': {
      id: '/api/admin-login'
      path: '/api/admin-login'
      fullPath: '/api/admin-login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-logout': {
      id: '/api/admin-logout'
      path: '/api/admin-logout'
      fullPath: '/api/admin-logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-session': {
      id: '/api/admin-session'
      path: '/api/admin-session'
      fullPath: '/api/admin-session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-contact': {
      id: '/api/delete-contact'
      path: '/api/delete-contact'
      fullPath: '/api/delete-contact'
      preLoaderRoute: typeof ApiDeleteContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-quote': {
      id: '/api/delete-quote'
      path: '/api/delete-quote'
      fullPath: '/api/delete-quote'
      preLoaderRoute: typeof ApiDeleteQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-contacts': {
      id: '/api/get-contacts'
      path: '/api/get-contacts'
      fullPath: '/api/get-contacts'
      preLoaderRoute: typeof ApiGetContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-quotes': {
      id: '/api/get-quotes'
      path: '/api/get-quotes'
      fullPath: '/api/get-quotes'
      preLoaderRoute: typeof ApiGetQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-contact': {
      id: '/api/submit-contact'
      path: '/api/submit-contact'
      fullPath: '/api/submit-contact'
      preLoaderRoute: typeof ApiSubmitContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-quote': {
      id: '/api/submit-quote'
      path: '/api/submit-quote'
      fullPath: '/api/submit-quote'
      preLoaderRoute: typeof ApiSubmitQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-contact': {
      id: '/api/update-contact'
      path: '/api/update-contact'
      fullPath: '/api/update-contact'
      preLoaderRoute: typeof ApiUpdateContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-quote': {
      id: '/api/update-quote'
      path: '/api/update-quote'
      fullPath: '/api/update-quote'
      preLoaderRoute: typeof ApiUpdateQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CoverageRoute: CoverageRoute,
  HowItWorksRoute: HowItWorksRoute,
  IndustriesRoute: IndustriesRoute,
  PricingRoute: PricingRoute,
  QuoteRoute: QuoteRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiDeleteContactRoute: ApiDeleteContactRoute,
  ApiDeleteQuoteRoute: ApiDeleteQuoteRoute,
  ApiGetContactsRoute: ApiGetContactsRoute,
  ApiGetQuotesRoute: ApiGetQuotesRoute,
  ApiSubmitContactRoute: ApiSubmitContactRoute,
  ApiSubmitQuoteRoute: ApiSubmitQuoteRoute,
  ApiUpdateContactRoute: ApiUpdateContactRoute,
  ApiUpdateQuoteRoute: ApiUpdateQuoteRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
